#!/bin/bash


if [ -z "$1" ]; then
    ROOT="/overlay/lower"
else
    ROOT="$1"
fi

if [ ! -d "${ROOT}" ]; then
    echo "${ROOT} directory not found"
    exit 1
fi

sudo mount -o remount,rw "${ROOT}" || { echo "error remounting ${ROOT} rw"; exit 1; }

if mountpoint -q /boot; then
    sudo mount -o remount,rw /boot || { echo "error remounting /boot rw"; exit 1; }
fi

for DIR in dev boot run proc sys; do
    if [ -d "${ROOT}"/"${DIR}" ] && ! mountpoint -q "${ROOT}"/"${DIR}"; then
        sudo mount --rbind /"${DIR}" "${ROOT}"/"${DIR}"
    fi
done

sudo IMCHROOTED="${ROOT}" chroot "${ROOT}"

for DIR in run proc sys boot dev; do
    if mountpoint -q "${ROOT}"/"${DIR}"; then
        sudo umount -lf "${ROOT}"/"${DIR}" 2>/dev/null
    fi
done

if mountpoint -q /boot; then
    sudo mount -o remount,ro /boot
fi

sudo mount -o remount,ro "${ROOT}"
sudo mount -t devpts devpts /dev/pts

exit 0
